### ISSUE TITLE
Issue Tracker

### ISSUE THREAD

**Issue by Number-3434** [RedCMD/RedCMD#2]
# Issue Tracker

These issues should have more attention.

---

### Backlog Candidates

These issues need upvoting. If they get 20 upvotes, they will be approved, and moved to the Backlog.

- _Please upvote these issues, to help improve our experience of VSCode._

- microsoft/vscode/issues/205503
- microsoft/vscode/issues/204926
- microsoft/vscode/issues/202386
- microsoft/vscode/issues/206615
- microsoft/vscode/issues/204018
- microsoft/vscode/issues/204216
- microsoft/vscode/issues/202909
- microsoft/vscode/issues/207159

Thank you 🙏.

<details>
<summary><h3>Backlog</h3>

- _These issues have received enough upvotes, and are now in the Backlog. Thank you to everyone who helped contribute!_</summary>

<p>

- microsoft/vscode/issues/204535

</p>
</details> 

---

# Tips

> [!tip]
> ## 1. Use Eyes 👀 Emoji
> If someone mentions you in an issue, react with the eyes emoji 👀 so that they know you've read it.
> 
> ## 2. Reusable Links
> You can define a custom link, like so:
> ```md
> [RedCMD]'s main repo.
> A link to [RedCMD]'s repo.
> 
> [RedCMD]: https://github.com/RedCMD/RedCMD
> ```
> Output: 
> > [RedCMD]'s main repo.
> > A link to [RedCMD]'s repo.
> > 
> > [RedCMD]: https://github.com/RedCMD/RedCMD
> 
> Then, each time you type `[RedCMD]`, it will create a link to his repository.
> 
> ## 3. <samp>&lt;samp&gt;</samp> and <kbd>&lt;kbd&gt;</kbd> Tags
> A `<samp>` tag is used to represent **sample output** from a program, like so:
> <samp>
> Some Sample Output
> </samp>
> 
> `<kbd>` tags are uses to represent **keyboard input**, e.g.
> <kbd><kbd>⌘ Cmd</kbd> + <kbd>⇧ Shift</kbd> + <kbd>S</kbd></kbd>

---

![Issue Views](https://komarev.com/ghpvc/?username=r-RedCMD-RedCMD-issues-2&label=Views:)

**Comment by RedCMD** [comment]
do you want me add this to my readme?

sadly the special rendering of `* [ ] https://github.com/microsoft/vscode/issues/205503` doesn't work in readme markdown previews
it only works within githubs `issues` pages

![image](https://github.com/RedCMD/RedCMD/assets/33529441/3dc36a00-1357-431c-9010-91e5205ff3fa)
even spreading them all out on separate task lines doesn't work

**Comment by Evileoo** [comment]
What do you think about this issue ?

https://github.com/microsoft/vscode/issues/205668

It got many likes but I feel it got lost in the jam of issues

**Comment by Number-3434** [comment]
@RedCMD
> do you want me add this to my readme?

No, I don't think that would work.

Maybe you could leave a link to this issue, or pin it.

**Comment by Number-3434** [comment]
> What do you think about this issue ?
> 
> [microsoft/vscode#205668](https://github.com/microsoft/vscode/issues/205668)
> 
> It got many likes but I feel it got lost in the jam of issues

Yeah, I've given it an upvote 👍.

**Comment by dimateos** [comment]
Nice lists, btw these are nice:
* Pin windows on top of other system ones: https://github.com/microsoft/vscode/issues/206809
* DependsOn and other task default values: https://github.com/microsoft/vscode/issues/205345
